// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/Create/A.vue')['default']
    AssortType: typeof import('./src/components/AssortType.vue')['default']
    B: typeof import('./src/components/Create/B.vue')['default']
    CreateInput: typeof import('./src/components/Create/CreateInput.vue')['default']
    CreateInputItem: typeof import('./src/components/Create/CreateInputItem.vue')['default']
    CreateTitle: typeof import('./src/components/Create/CreateTitle.vue')['default']
    CreateType: typeof import('./src/components/Create/CreateType.vue')['default']
    DetailList: typeof import('./src/components/DetailList/DetailList.vue')['default']
    DetailListItem: typeof import('./src/components/DetailList/DetailListItem.vue')['default']
    EditExpend: typeof import('./src/components/EditExpend/EditExpend.vue')['default']
    EditInput: typeof import('./src/components/EditExpend/EditInput.vue')['default']
    FiltrateList: typeof import('./src/components/Statistics/FiltrateList.vue')['default']
    HomeBottomBar: typeof import('./src/components/Home/HomeBottomBar.vue')['default']
    HomeDetail: typeof import('./src/components/Home/HomeDetail.vue')['default']
    HomeDetailItem: typeof import('./src/components/Home/HomeDetailItem.vue')['default']
    HomeTitle: typeof import('./src/components/Home/HomeTitle.vue')['default']
    HomeType: typeof import('./src/components/Home/HomeType.vue')['default']
    HomeTypeContainer: typeof import('./src/components/Home/HomeTypeContainer.vue')['default']
    LeftRightMove: typeof import('./src/components/LeftRightMove.vue')['default']
    ListItem: typeof import('./src/components/Statistics/list-item.vue')['default']
    Prompt: typeof import('./src/components/Prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTime: typeof import('./src/components/Statistics/SelectTime.vue')['default']
    Test: typeof import('./src/components/Create/Test.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
